### ISSUE TITLE
add bookmark support

### ISSUE THREAD

**Issue by spookyGh0st** [SpyceTewan/AndroidMapper#1]
Just want to let you know, that bookmark support would be really great, since that lets other tools build on top of your mapper.

**Comment by StefanH-AT** [comment]
I will look into that after I implemented the basic features.

**Comment by StefanH-AT** [comment]
Can you clarify how this bookmark support should be implemented? Where does it appear in the json model and what is its structure?

**Comment by spookyGh0st** [comment]
It appears in the Difficulty file with a structure like this:

` { 
     "_BPMChanges": [], 
     "_bookmarks": [ 
         { 
             "_name": "sample bookmark at beat 4", 
             "_time": 4.0 
         }, 
         { 
             "_name": "sample bookmark at beat 20", 
             "_time": 20.0 
         } 
     ], 
     "_events": [], 
     "_notes": [], 
     "_obstacles": [], 
     "_version": "2.0.0" 
 }
`
